// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SoftStocksData
{
    public partial class KeyboardRecommendationModel
    {
        /// <summary>
        /// model input class for KeyboardRecommendationModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"model_number")]
            public float Model_number { get; set; }

            [ColumnName(@"supplier_id")]
            public float Supplier_id { get; set; }

            [ColumnName(@"quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"description")]
            public string Description { get; set; }

            [ColumnName(@"price")]
            public float Price { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for KeyboardRecommendationModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"model_number")]
            public float Model_number { get; set; }

            [ColumnName(@"supplier_id")]
            public uint Supplier_id { get; set; }

            [ColumnName(@"quantity")]
            public float Quantity { get; set; }

            [ColumnName(@"description")]
            public uint Description { get; set; }

            [ColumnName(@"price")]
            public float Price { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("KeyboardRecommendationModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
